const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Behaviors.Flash,
		C3.Behaviors.Timer,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.AJAX.Cnds.OnError,
		C3.Plugins.Touch.Exps.TouchCount,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Sprite.Exps.IID,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Sprite.Exps.AnimationFrameTag,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Arr.Exps.Back,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{golge: 0},
	{arkaplan: 0},
	{spbeyaz: 0},
	{mebLogo: 0},
	{emegigecenler: 0},
	{about: 0},
	{reference: 0},
	{Sine: 0},
	{Logo: 0},
	{tebrikler: 0},
	{Flash: 0},
	{soruZemin: 0},
	{Timer: 0},
	{puanZemin: 0},
	{dogruYanlis: 0},
	{goodJoob: 0},
	{info: 0},
	{ilerlemeZemin: 0},
	{ilerlemeDolgu: 0},
	{spbeyaz2: 0},
	{Touch: 0},
	{Mouse: 0},
	{Browser: 0},
	{Audio: 0},
	{AJAX: 0},
	{rastgeleSayilar: 0},
	{kelimeler: 0},
	{kelimeSayi: 0},
	{Keyboard: 0},
	{btn_basla: 0},
	{btn_anasayfa: 0},
	{btn_emegigecenler: 0},
	{btn_kaynakca: 0},
	{btn_replay: 0},
	{durum: 0},
	{btn_ses: 0},
	{btn_tamekran: 0},
	{btn_Bilgi: 0},
	{btn_next: 0},
	{btn_ham: 0},
	{score: 0},
	{ipucu: 0},
	{ivirzivirtxt: 0},
	{txt_sayac: 0},
	{txt_durum: 0},
	{txt_puanEfekt: 0},
	{satirNo: 0},
	{animSure: 0},
	{txt_ipucuSatir: 0},
	{filmSeridi: 0},
	{girisTemelX: 0},
	{girisTemelY: 0},
	{karakter: 0},
	{sag_alt_yazi: 0},
	{sehirKare: 0},
	{sehirler: 0},
	{seritCerceve: 0},
	{arka_1: 0},
	{arka_4: 0},
	{arka_2: 0},
	{arka_3: 0},
	{arka_5: 0},
	{arka_6: 0},
	{arka_7: 0},
	{arka_8: 0},
	{arka_9: 0},
	{arka_10: 0},
	{arka_12: 0},
	{arka_14: 0},
	{arka_15: 0},
	{arka_16: 0},
	{arka_17: 0},
	{yasam: 0},
	{omur: 0},
	{hizX: 0},
	{hizY: 0},
	{pirilti: 0},
	{boyut: 0},
	{parlaklik: 0},
	{piriltiYildiz: 0},
	{finalScore: 0},
	{finalScoreKutu: 0},
	{ButonAilesi: 0},
	{AnaSayfaGorseller: 0},
	{oyunSprites: 0},
	{oyunTexts: 0},
	{girisHareketZamani: 0},
	{girisDerinlikX: 0},
	{girisDerinlikY: 0},
	{suruklemeHareket: 0},
	{suruklemeTiklamaBekleme: 0},
	{suruklemeDelta: 0},
	{suruklemeSonX: 0},
	{suruklemeBaslangicX: 0},
	{suruklemeAktif: 0},
	{suruklemeBasili: 0},
	{tamEkranDurum: 0},
	{oyunDerinlikX: 0},
	{oyunDerinlikY: 0},
	{gosterilenPuan: 0},
	{puanBaslangic: 0},
	{kazanilanPuan: 0},
	{puanAnimSure: 0},
	{puanAnimAktif: 0},
	{puanEfektX: 0},
	{puanEfektY: 0},
	{menuAcik: 0},
	{tamamlananSehir: 0},
	{soruNo: 0},
	{aktifSehir: 0},
	{secilenSehir: 0},
	{ipucuNo: 0},
	{ipucuSure: 0},
	{oyunDurum: 0},
	{seritKayma: 0},
	{veriHazir: 0},
	{bilgiAcik: 0},
	{yanlisBekleme: 0},
	{musicDurum: 0},
	{tiklanabilir: 0},
	{toplamPuan: 0},
	{toplamSehir: 0}
];

self.InstanceType = {
	golge: class extends self.ISpriteInstance {},
	arkaplan: class extends self.ISpriteInstance {},
	spbeyaz: class extends self.ISpriteInstance {},
	mebLogo: class extends self.ISpriteInstance {},
	emegigecenler: class extends self.ISpriteInstance {},
	about: class extends self.ISpriteInstance {},
	reference: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	tebrikler: class extends self.ISpriteInstance {},
	soruZemin: class extends self.ISpriteInstance {},
	puanZemin: class extends self.ISpriteInstance {},
	dogruYanlis: class extends self.ISpriteInstance {},
	goodJoob: class extends self.ISpriteInstance {},
	info: class extends self.ISpriteInstance {},
	ilerlemeZemin: class extends self.ISpriteInstance {},
	ilerlemeDolgu: class extends self.ISpriteInstance {},
	spbeyaz2: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	rastgeleSayilar: class extends self.IArrayInstance {},
	kelimeler: class extends self.IArrayInstance {},
	kelimeSayi: class extends self.IArrayInstance {},
	Keyboard: class extends self.IInstance {},
	btn_basla: class extends self.ISpriteInstance {},
	btn_anasayfa: class extends self.ISpriteInstance {},
	btn_emegigecenler: class extends self.ISpriteInstance {},
	btn_kaynakca: class extends self.ISpriteInstance {},
	btn_replay: class extends self.ISpriteInstance {},
	btn_ses: class extends self.ISpriteInstance {},
	btn_tamekran: class extends self.ISpriteInstance {},
	btn_Bilgi: class extends self.ISpriteInstance {},
	btn_next: class extends self.ISpriteInstance {},
	btn_ham: class extends self.ISpriteInstance {},
	score: class extends self.ITextInstance {},
	ipucu: class extends self.ITextInstance {},
	ivirzivirtxt: class extends self.ITextInstance {},
	txt_sayac: class extends self.ITextInstance {},
	txt_durum: class extends self.ITextInstance {},
	txt_puanEfekt: class extends self.ITextInstance {},
	txt_ipucuSatir: class extends self.ITextInstance {},
	filmSeridi: class extends self.ISpriteInstance {},
	karakter: class extends self.ISpriteInstance {},
	sag_alt_yazi: class extends self.ISpriteInstance {},
	sehirler: class extends self.ISpriteInstance {},
	seritCerceve: class extends self.ISpriteInstance {},
	arka_1: class extends self.ISpriteInstance {},
	arka_4: class extends self.ISpriteInstance {},
	arka_2: class extends self.ISpriteInstance {},
	arka_3: class extends self.ISpriteInstance {},
	arka_5: class extends self.ISpriteInstance {},
	arka_6: class extends self.ISpriteInstance {},
	arka_7: class extends self.ISpriteInstance {},
	arka_8: class extends self.ISpriteInstance {},
	arka_9: class extends self.ISpriteInstance {},
	arka_10: class extends self.ISpriteInstance {},
	arka_12: class extends self.ISpriteInstance {},
	arka_14: class extends self.ISpriteInstance {},
	arka_15: class extends self.ISpriteInstance {},
	arka_16: class extends self.ISpriteInstance {},
	arka_17: class extends self.ISpriteInstance {},
	pirilti: class extends self.ISpriteInstance {},
	piriltiYildiz: class extends self.ISpriteInstance {},
	finalScore: class extends self.ISpriteInstance {},
	finalScoreKutu: class extends self.ISpriteInstance {},
	ButonAilesi: class extends self.ISpriteInstance {},
	AnaSayfaGorseller: class extends self.ISpriteInstance {},
	oyunSprites: class extends self.ISpriteInstance {},
	oyunTexts: class extends self.ITextInstance {}
}